src/midgard/point2.cc, src/midgard/pointll.cc, src/midgard/tiles.cc, test/encode.cc, valhalla/midgard/point2.h, valhalla/midgard/pointll.h
points got boiled down to an std pair a pr ago. but i had messed up how that worked so that it actually didnt work using the pair. so i've fixed that and added an apprx equals method which is very useful in testing but could be useful for other geometric algorithms. i also fixed up a bit the closest point code to be a little less "c style" looking. all said and done it allowed me to delete a lot of code an really simplify the point classes. this was needed for using the encoding of shape in prs taht i'll add in a minute or two.
=> updates for point equality and interplay with polyline encoding

.gitignore, Makefile.am, test/logging.cc, valhalla/midgard/logging.h
this logger is thread safe and allows you to log to stdout with pretty colors or to file. stdout is already thread safe so not much care was needed there. the file mechanism is not and therefore needed mutexs to synchronize. also the file logger needs to be configured to close and reopen the file on a regular interval. this is useful because if the program segfaults you dont get anything in your file log if you dont periodically close it and reopen it. the default config is for it to do this every 5 minutes. there are really only two interfaces to the whole framework that you need.
1. at the beginning of your program configure logging, after you do this you can never configure it again some example would be:
//write log output to the file test.log and reopen the file ever 60 sec …
=> add logging framework

Makefile.am, src/midgard/logging.cc, test/logging.cc, valhalla/midgard/logging.h, valhalla/midgard/util.h
~~this sucks. i want the logger to be header only so that each project can configure it seprately however this turns out to not make any sense. if a singleton lives in a header only and a downstream library initializes it what happens in the upstream? my brain hurts and this makes it work so we'll have to configure it once in midgard live with it configured that way for all other projects that use it. bah~~
i havent tested it yet but i thought about it a lot last night and because the macros are in the header that means that each time they get included in a compilation unit the preprocessor directives for that compilation will be evaluated. that means you should be able to compile it multiple times and change the logging level in the given library. in fact i think we've proven this works …
=> logger fixes for using accross multiple files

valhalla/midgard/logging.h
sometimes when you want to log something it requires a little bit computation to determine what to log, ifs some arithmetic, whatever. it would be nice if before we even compile any of that stuff we could know if it were going to be logged anyway based on the level that is globally defined. this pr enables that. heres a concrete example from oden:
https://github.com/valhalla/odin/pull/11
=> set defines

src/midgard/logging.cc, test/logging.cc, valhalla/midgard/logging.h
this less you log with a custom log level:
2015/02/02 16:18:09.516777 [CUSTOM] hi my name is: 47610380150528
2015/02/02 16:18:09.516798 [ERROR] hi my name is: 47610380150528
2015/02/02 16:18:09.516783 [ERROR] hi my name is: 47610382251776
2015/02/02 16:18:09.516783 [ERROR] hi my name is: 47610519881472
2015/02/02 16:18:09.516725 [CUSTOM] hi my name is: 47610378049280
2015/02/02 16:18:09.516873 [ERROR] hi my name is: 47610378049280
2015/02/02 16:18:09.526927 [WARN] hi my name is: 47610519881472
note this shows an example of how to use logging without the macros. it is highely discouraged to use logging without the macros as it circumvents the mechanism by which we set the verbosity of a build. in other words please dont use logging without using the macros unless you really really must log …
=> add custom log level and test for it

src/midgard/aabb2.cc, src/midgard/tiles.cc, test/aabb2.cc, valhalla/midgard/tiles.h
(any one corner must lie on an opposing side of the line than the others).  Update test to have many different cases for segment intersecting a bounding box.
Add a AreNeighbors convenience method to Tiles.
=> Update AABB2 intersection with a segment to use half-space 

src/midgard/util.cc, test/util.cc, valhalla/midgard/util.h
openbsd doesnt have procfs. you can apparently install it but by default it is now removed. easiest way to make this pass without really worrying about how to get this info from os's that donst support it is to disable it for those os's. we dont make use of it for anything mission critical so (more for instrumentation) so its fine to disable if its not supported.
=> some os's dont have /proc. this fixes #49

src/midgard/obb2.cc, test/obb2.cc, valhalla/midgard/obb2.h
Accepting Point2 or PointLL. Update tests to include a PointLL test.
This is the first of several midgard updates to use templates for coordinate type (Point2 or PointLL). Doing this one first since it is not yet used anywhere.
=> Make this a template class

src/midgard/aabb2.cc, src/midgard/clipper2.cc, src/midgard/ellipse.cc, src/midgard/linesegment2.cc, src/midgard/pointll.cc, src/midgard/polyline2.cc, src/midgard/tiles.cc, test/aabb2.cc, test/ellipse.cc, test/linesegment2.cc, test/polyline2.cc, test/tiles.cc, valhalla/midgard/aabb2.h, valhalla/midgard/clipper2.h, valhalla/midgard/ellipse.h, valhalla/midgard/linesegment2.h, valhalla/midgard/pointll.h, valhalla/midgard/polyline2.h, valhalla/midgard/tiles.h
Template classes use Point2 or PointLL. DIffer mostly in distance computations.
Remove a couple methods (like tile Area) that do not have consistency between coordinate types.
=> Template class so geometric objects accept a coordinate type

src/midgard/tiles.cc, test/tiles.cc
Use `(x, y)` i.e. `(lng, lat)`
=> Fix wrong coordinate order

src/midgard/pointll.cc, src/midgard/util.cc, test/encode.cc, test/util.cc, valhalla/midgard/pointll.h, valhalla/midgard/util.h
this changes the way resampling works. first its a simpler algorithm. second, its more accurate at the cost of some heavier trig functions. ive tested this an it has zero impact where its used (getting elevation data) as that is dominated by the time to fetch values from memory mapped files. it works by computing the distance along the great arc segment instead of the flat earth segment.
i also did some template work to allow lists in addition to vectors from encode/decode which is nice because it removes the possibility of realloc. the reason for that is because when resampling you cant know how many points you'll have without first computing the length of the linestring and frankly for serializing that in a request or using it in mjolnir we dont need indexed access to individual points. …
=> more accurate resampling

src/midgard/aabb2.cc, src/midgard/grid.cc, test/grid.cc, valhalla/midgard/aabb2.h, valhalla/midgard/grid.h
what was happening is that you dont know which side of the intersected range is at the beginning or ending of a given linesegment. so to find the subset we clip the segment to the bounding box. we then find where those clipped points lie in terms of row col within the grid. the problem is when you loop over that range, if you ened up clipping the one side of the segment on the extreme edge (most positive x or y aligned edge) one of the variables in the loop range will be the dimension of the grid itself which is essentially out of bounds.
so the fix was simple. change the range to < instead of <= and add 1 to the end of the range but clamp it to the dimension in case it goes over that.
this was very hard to explain so if you didnt understand anything i am saying then feel free to rubber …
=> fix grid intersect out of bounds

src/midgard/grid.cc, src/midgard/pointll.cc, test/pointll.cc, valhalla/midgard/grid.h, valhalla/midgard/pointll.h
this adds the ability to get the mid point along the geodesic between two spherical coordinates. it adds test for that as well. oh i should mention that this mid point thing is useful for interfacing with other systems which use a canonical interpretation of lat,lon projected geometries. we make a simplification by assuming that the world is flat, they, properly do not. this will be used in transit_fetcher to do proper tile intersection with transit.land geographies
also changes the way grid intersection was done to allow for more efficient computation of the intersecting subcells. this approach will also be used to return information about the intersecting neighbor grids should a segment leave the grid in question.
=> sphereical coordinate midpoint, grid intersection efficiency and neighbors

src/midgard/point2.cc, src/midgard/tiles.cc, test/tiles.cc
two problems:
* the tests were too brittle because when computing intersections precision plays a role in whether or not a given subtile was intersected or not. the fix was simple, change the tests so that they allow the answer to be equal to or a subset of the expected answer.
* the math for following the line through the grid was wrong. bresenhams works by moving the endpoint of the line as you go through the grid (in the simplified algorithm). but that skips/adds subtiles that arent intersected by the actual floating point line. to fix that i changed the alogirhtm to compute the distance of the next two possible grid center points to the original line. but since the original line was moving this was messing up the calculation for small lines. so i keep the line as is and iterate …
=> fix broken subtile intersection

src/midgard/polyline2.cc, src/midgard/tiles.cc, src/midgard/util.cc, test/util.cc, valhalla/midgard/polyline2.h, valhalla/midgard/util.h
this pr makes sure to resample long edges' shapes for binning so that we dont incorrectly bin portions of the edge.
because of geodesics, straight lines between two points on a sphere, dont follow the same rules as straight lines in the plane, when we bin edges into our planar grid we must do a little more work. this pr attempts to approximate a long geodesic via piecewise approximation that should be fine enough to remove incorrectly binned sections of an edge.
=> square peg, round hole

src/midgard/tiles.cc
the previous PR had a bug *gasp*, i was comparing meters to degrees, and then resampling shape in degrees... this doesnt make any sense.
so ive changed this to compare meters to meters and resample in meters because that is what the function expects, duh. sorry for the mistake!
=> must match units when comparing

src/midgard/pointll.cc, src/midgard/tiles.cc, test/tiles.cc, valhalla/midgard/tiles.h
for `loki` to to check bins of tiles we need a means of iterating over subdivision within the `Tiles` object. optimally we would want to iterate over the closest ones to the input point first. the reason we'd want to do this is so that we can terminate the iteration as soon as possible. basically if you find a candidate in one subdivsion/bin and its `x` distance away from the input point. as soon as you hit a subdivision whose closest point to the input is greater than `x` then you know you can stop and not even consider that subdivsion/bin or any subsequent once (since its closest first).
the tests are currently working but the last one fails because of a precision issue in sorting..i'll resolve that before merging of course. i also need to add a few more tests. then we can start using …
=> closest first subdivision iteration

src/midgard/tiles.cc, test/tiles.cc
sometimes two points on a linestring are so close together that their slope cannot be accurately computed. this is not good because it causes algorithms similar to bresenhams to go past the target pixel. the thing about degenerate cases is that they are very short. so the source pixel and the target pixel must be close together. we already had a check in there for when the source and target were the same pixel. we didnt check if the source and target were adjacent pixels though (this should be pretty common). so i've added that check here. it should not only fix the bug but also make the binning faster.
note that the fix essentially involves figuring out when something is trivial and hardcoding the answers for those cases. this is what gives the speedup. it turns out that the degenerate …
=> subtile intersection to fix binning

src/midgard/gridded_data.cc, valhalla/midgard/gridded_data.h
These overwhelm the average (s[0]) and distort the intersect method. Set to a value just above the
threshold for a tile corner that has the max_value set.
=> Check for values equal to the max_value

src/midgard/logging.cc
this is useful when you want your program to output to `stdout` or even part of a pipe of things (to be consumed down stream) but you still want to periodically log status messages that dont go down stream. the solution is to log status to `stderr` so the regular output isnt affected by them.
=> add stderr logger

valhalla/midgard/sequence.h
we also have the option to warn in baldr graphreader if some of the blocks in the archive are skipped.
=> be robust to tars that have corruption or are concatinated archives

src/midgard/util.cc, test/util_midgard.cc, valhalla/midgard/util.h
this allows using decoding functions with a pointer to some bytes rather than requiring those bytes live in an `std::string` this can give a lot of savings over large datasets as it avoids copying bytes around.
thanks to @TeXitoi for suggesting it in valhalla/baldr#298
=> expand shape decoding to allow for raw char buffer as input

src/midgard/pointll.cc, test/pointll.cc
This is now similar code to the project method in loki search. Added a test method.
Note - the only place this is currently used is in transit builder where it finds the closest point to a stop lat,lng.
Fixes #101
=> Scale the longitude distance by the cos of the latitude. 

src/midgard/tiles.cc, test/tiles.cc, valhalla/midgard/tiles.h
There's a `Tiles::Intersect` function which returns the tiles and subdivisions (a.k.a. bins) intersecting a linestring. This adds an overload of that which takes a bounding box instead. This might be helpful for other parts of the code which want to iterate over the tiles and bins within an area.
@kevinkreiser could you review, please?
=> Add function for tiles intersecting a bounding box

src/midgard/tiles.cc, test/tiles.cc
This issue cropped up where a bounding box which actually only intersected one tile was being detected as intersecting two. This was happening because the division was resulting in a number like `1809.99988`, which was (correctly) being `floor`ed to `1809` although the expected result was `1810`.
Added test for the same.
@kevinkreiser could you take a look, please?
=> Multiply before dividing in order to preserve precision. 

src/midgard/pointll.cc, src/midgard/util.cc, valhalla/midgard/constants.h
M_PI is not always available (e.g. MS compilers) so lets define a constexpr and use that where needed.
=> Remove M_PI and add a constexpr in its place.
