valhalla/midgard

src/midgard/util.cc
valhalla/midgard/util.h

@dnesbitt61 @kevinkreiser @gknisely

Added GetTurnDegree

---

.gitignore
Makefile.am
src/midgard/pointll.cc
src/midgard/util.cc
test/pointll.cc
test/util.cc
valhalla/midgard/pointll.h
valhalla/midgard/util.h

@dnesbitt61 @kevinkreiser @gknisely

Added util.GetTurnDegree  and simple heading tests

---

test/util.cc
valhalla/midgard/util.h

Added coments for GetTime and GetTurnDegree
@dnesbitt61 @gknisely @kevinkreiser

Added test for GetTime

---

src/midgard/distanceapproximator.cc
src/midgard/pointll.cc
test/distanceapproximator.cc
test/pointll.cc
valhalla/midgard/constants.h
valhalla/midgard/distanceapproximator.h
valhalla/midgard/pointll.h
valhalla/midgard/polyline2.h

Change units of distance from kilometers to meters.

---

Makefile.am
test/logging.cc
valhalla/midgard/logging.h

simplified the logging a bit to remove boilerplate that was already in stl. make test more robust to check more code branches

remove cruff

---

src/midgard/point2.cc
src/midgard/util.cc
test/encode.cc
test/util.cc
valhalla/midgard/util.h

add equality with epsilon util, update higher precision for encode/decode, add tests

---

README.md
docs/index.md
docs/test_coverage.md

to actually look at what the stuff will look like go here: https://github.com/valhalla/midgard/tree/kk_readme and scroll down on the page to see the rendered README markdown

updates to the readme to make it relevant

---

src/midgard/util.cc
test/util.cc
valhalla/midgard/util.h

add memory status method so we can check memory use

---

src/midgard/pointll.cc
test/pointll.cc

Fixed the heading calculation

---

src/midgard/tiles.cc
test/tiles.cc
valhalla/midgard/tiles.h

Each depends on a tile map - a vector of bool indicating whether each tile is empty (false) or has data (true).

Add methods to create a connectivity map and to test if a path exists between 2 tiles

---

src/midgard/tiles.cc
valhalla/midgard/tiles.h

takes the connectivity map as input now and colors it in place basically the only changes. the connectivity map is then owned by the singlton in baldr, pr incomming

small updates to tile connectivity map for singleton use

---

test/util.cc
valhalla/midgard/util.h

for heading and other circular degree type things..

add circular range clamp util function

---

src/midgard/aabb2.cc
test/aabb2.cc
valhalla/midgard/aabb2.h

Update comments and improve the Create method (better use of C++ 11).

Add intersect method with LineSegment2.

---

src/midgard/linesegment2.cc
test/linesegment2.cc
valhalla/midgard/linesegment2.h

Cleanup comments and formatting too

Add method to test if line segment intersects a convex polygon.

---

src/midgard/util.cc
test/util.cc
valhalla/midgard/util.h

we can use this method to evenly sample along a piece of road so as to get an idea of how much up and down it does along its geometry.
heres what it looks like at 100 meters: http://bl.ocks.org/anonymous/raw/7229bd02671158bfc2d0/
heres what it looks like at 60 meters: http://bl.ocks.org/d/641e93b6cebd45cfb10c

add linestring resampling utility method

---

test/util.cc

had these in before i merged the pr but stupidly didnt commit them... sorry all

extended tests for resample

---

.gitignore
Makefile.am
test/sequence.cc
valhalla/midgard/sequence.h

i have tests for sequence that i will add as well

move sequence to midgard. refactor memmap bits into confined class

---

scripts/dependencies.sh
test/sequence.cc
valhalla/midgard/sequence.h

@ptpt if you'd like we can rebase this to put you as the commit author
done :o)

sequence tests and operator fixes

---

src/midgard/util.cc
valhalla/midgard/util.h

yeah copy around possibly massive vectors

---

Makefile.am
src/midgard/aabb2.cc
src/midgard/grid.cc
test/aabb2.cc
test/util.cc
valhalla/midgard/aabb2.h
valhalla/midgard/grid.h
valhalla/midgard/util.h

this pr adds methods to figure answer that question. i will add tests before merging this pr to prove that it works, but i didnt want to write them until i was sure the interface (return type) was what i wanted to use in loki and mjolnir.
it also adds a method loki can use to intersect a circle with a grid object. again,  not sure if this will be the final interface, and needs a few more methods like, one to get the neighboring grid and one to use the returned index to get a sub cell of a grid.
after making use of it for a while to make the changes in mjolnir and loki i should be able to work out the interface kinks and merge this pr early next week if you all think its ok

what subsections of a tile would shape intersect?

---

.gitignore
Makefile.am
src/midgard/grid.cc
test/grid.cc
valhalla/midgard/grid.h

this adds tests for and fixes to a bunch of bugs i found with the grid intersection.
also added a bool that gets passed back letting you know if the linestring leaves the given grid. this is useful in mjolnir to do additional tests against neighboring grids for edge binning

tests and bug fixes for grid line intersection

---

test/grid.cc

im trying to track down a crash in validator when using this to bin edges inside of a given tile. i was really hoping that this would show a bug but so far i havent found one here.

add random linestring intersection test

---

valhalla/midgard/util.h

this is convenient for a test i am writing in mjolnir. basically this class wraps a pointer to look like an stl container, the main purpose of it is so you can do for eachs but its also nice to use vector like operators on it without having to do `container.begin()[i]` you can just do `container[i]`

allow access via [] operator

---

src/midgard/tiles.cc
valhalla/midgard/tiles.h

Remove tilelist_ class data member and construct local tile list within TileList method.

Make TileList a const method.

---

src/midgard/util.cc
test/util.cc

Protect against divide by zero for GetTime

---

Makefile.am
src/midgard/gridded_data.cc
valhalla/midgard/gridded_data.h

Derived from Tiles. Holds a single value per tile. Has an initial contouring method (based on Paul Bourke's conrec algorithm). Initial use is for isochrones.

GriddedData class

---

src/midgard/ellipse.cc
test/pointll.cc
test/vector2.cc

all of these were precision degeneracy related. there is probably a lot more of this and im not sure in practice that it will matter but i am sure we dont test all of it.

precision fixes for 32bit test failures

---

test/pointll.cc

in release mode the angle computations were right on the edge for some of the tests. so i've relaxed it to be within a degree.

more 32bit release only precision issues

---

.gitignore
Makefile.am
src/midgard/gridded_data.cc
test/gridded_data.cc
valhalla/midgard/gridded_data.h

and add a test to start exercising it

fix some isochrone bugs

---

src/midgard/gridded_data.cc
src/midgard/point2.cc
src/midgard/pointll.cc
src/midgard/tiles.cc
test/gridded_data.cc
valhalla/midgard/gridded_data.h
valhalla/midgard/point2.h
valhalla/midgard/pointll.h

this is the first piece. the test should now be able to be fully written and we can preview some geojson. ill add that to this pr.

piece the segments together

---

src/midgard/gridded_data.cc
src/midgard/polyline2.cc
test/gridded_data.cc
valhalla/midgard/gridded_data.h
valhalla/midgard/polyline2.h

im not sure what dumbness i was thinking before but having the hash lookup for the first phase of merging contour segments was all we needed to make sure we merge them all. all i needed to do was add another step that checked that after adding to one (as single point) whether or not that point made it possible to connect another already existing sub-segment. doing this extra step ensures that all rings will be complete (in so far as possible) without having to look at merging more of them in a subsequent step.

yeah this is way faster

---

valhalla/midgard/sequence.h

small struct for memory mapping tar files. scans through the tar to index it so you can easily ask if a file exists within a tar, how large it is and where its is mapped in memory.

add mmap'd tar loading support to sequence

---

test/sequence.cc
valhalla/midgard/sequence.h

make find return an interator

---

src/midgard/distanceapproximator.cc
src/midgard/point2.cc
src/midgard/pointll.cc
valhalla/midgard/distanceapproximator.h
valhalla/midgard/point2.h
valhalla/midgard/pointll.h

The modifications cited in valhalla/loki#170

Expose a little bit of code in the headers to improve inlining.
